name: 'exchange-rates-api-compose'
services:
  postgres:
    image: postgres:17.2
    container_name: postgres
    environment:
      POSTGRES_DB: exchange_rates_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  exchange-rates-api:
    build: .
    container_name: exchange-rates-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING.PROFILES.ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/exchange_rates_db
      EXCHANGE_RATES_EXTERNAL_API_KEY: ${EXCHANGE_RATES_EXTERNAL_API_KEY}
